# This file is machine-generated - editing it directly is not advised

[[Multisets]]
git-tree-sha1 = "3c478ef38e8d858aed1aeba3a2043be72154e3c7"
uuid = "3b2b4ff1-bcff-5658-a3ee-dbcf1ce5ac09"
version = "0.4.2"
